@url = http://localhost:2243

###
POST {{url}}/api/passtypes
Content-Type: application/json

{
    "name": "Wiele wejść",
    "price": 250,
    "entries": 1000,
    "isOpen": true
}

###
GET {{url}}/api/passtypes/

###
DELETE {{url}}/api/passtypes/71b21932-cb99-4f4b-80cd-0e3ce239ea91

###
POST {{url}}/api/students/sign-in
Content-Type: application/json

{
    "Id": "233dd7e0-23a0-47b1-849c-d3b3ee9e4afe"
}

###
GET {{url}}/api/passes/71b21932-cb99-4f4b-80cd-0e3ce239ea91